version: 0.0.1{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\(GameEngines)\$env:CONFIGURATION\(3D Engine).exe C:\projects\(GameEngines)\Game\.
artifacts:
- path: 3D Engine\Game
  name: GameEngines
deploy:
- provider: GitHub
  auth_token:
    secure: epekEMuEi7wy20Py93w3I9c4FfnhPJxdz1NmdDvYYoqGpEIkwjomuEbXpz0/FuEHU/fwHezJb/9XFneJa9ZbvkI9L+9VlKgRQS+0D+RGsyQ=
  repository: albertmas/GameEngines
  artifact: 3D Engine
  draft: true